#!/usr/bin/env python3
"""Turn a box-built Isaac stage into a Nav2 map, exactly.

    ros2 run vica_description make_map_from_stage \\
        --stage <stage.usd> --out <dir>/<name>

Reads only the stage file. No simulator, no robot, no SLAM.

Mapping a course by driving it is the honest procedure for a building, and the
wrong one for a measurement. The width course exists to find the corridor width
where driving stops working, and SLAM contributes its own error to every wall it
places -- so a lane that failed would leave the question of whether it failed
because it is 0.70 m or because the map thought it was 0.66. Building the grid
from the geometry removes that variable, and leaves the controller as the only
thing under test.

That is a deliberate departure from how the robot gets its maps, and it is only
defensible for a purpose-built course. A stage meant to stand in for a real
building should still be mapped with cartographer, the way the robot is.

Quantisation is reported rather than hidden. At 0.05 m a 0.70 m lane becomes
some whole number of cells, and which one depends on where the walls fall
against the grid. A cell is occupied when a wall covers its centre, which
rounds in both directions instead of always outward -- growing every wall by
half a cell would narrow every lane by one, which is the very quantity being
measured.
"""

import argparse
import math
import os
import sys

import numpy as np

FREE, OCCUPIED, UNKNOWN = 254, 0, 205
WALL_MIN_TOP = 0.15

# The robot is made of boxes too, and they stand well above the floor line.
#
# Without this exclusion its own chassis, mast and wheels are read as walls and
# baked into the map at the spawn, which is a robot-shaped obstacle exactly
# where the robot is. The planner then answers "Start occupied" to every goal in
# 0.1 seconds, and the run looks like a controller that cannot leave the start.
ROBOT_SUBTREE = "/World/VICA"


def read_walls(stage_path):
    from pxr import Usd, UsdGeom

    stage = Usd.Stage.Open(stage_path)
    if stage is None:
        raise RuntimeError(f"could not open {stage_path}")
    walls = []
    for prim in stage.Traverse():
        if str(prim.GetPath()).startswith(ROBOT_SUBTREE):
            continue
        if not prim.IsA(UsdGeom.Cube):
            continue
        xf = UsdGeom.Xformable(prim)
        m = xf.ComputeLocalToWorldTransform(Usd.TimeCode.Default())
        t = m.ExtractTranslation()
        size = UsdGeom.Cube(prim).GetSizeAttr().Get() or 1.0
        w = m.GetRow3(0).GetLength() * size
        h = m.GetRow3(1).GetLength() * size
        d = m.GetRow3(2).GetLength() * size
        if t[2] + d / 2 < WALL_MIN_TOP:
            continue
        walls.append((t[0] - w / 2, t[1] - h / 2, t[0] + w / 2, t[1] + h / 2))
    if not walls:
        raise RuntimeError("no walls found -- is this a stage built from boxes?")
    return walls


def rasterise(walls, resolution):
    x0 = min(w[0] for w in walls)
    y0 = min(w[1] for w in walls)
    x1 = max(w[2] for w in walls)
    y1 = max(w[3] for w in walls)
    cols = int(math.ceil((x1 - x0) / resolution))
    rows = int(math.ceil((y1 - y0) / resolution))
    grid = np.full((rows, cols), FREE, dtype=np.uint8)

    # Cell centres, so a wall claims a cell when it covers the middle of it.
    cx = x0 + (np.arange(cols) + 0.5) * resolution
    cy = y0 + (np.arange(rows) + 0.5) * resolution
    for ax, ay, bx, by in walls:
        i0 = np.searchsorted(cx, ax)
        i1 = np.searchsorted(cx, bx)
        j0 = np.searchsorted(cy, ay)
        j1 = np.searchsorted(cy, by)
        grid[j0:j1, i0:i1] = OCCUPIED
    return grid, (x0, y0)


def free_runs(grid, resolution, axis):
    """Lengths of consecutive free cells, for reporting what the grid became."""
    runs = []
    lines = grid if axis == 0 else grid.T
    for line in lines:
        n = 0
        for v in line:
            if v == FREE:
                n += 1
            elif n:
                runs.append(n * resolution)
                n = 0
        if n:
            runs.append(n * resolution)
    return runs


def write_pgm(path, grid):
    # PGM's first row is the top of the image, and map_server reads the top row
    # as the highest y. The grid is built with row 0 at the lowest y, so it is
    # flipped on the way out. Getting this wrong mirrors the map vertically and
    # nothing complains -- it just never localises.
    flipped = np.flipud(grid)
    with open(path, "wb") as fh:
        fh.write(b"P5\n")
        fh.write(b"# generated by make_map_from_stage from the stage geometry\n")
        fh.write(f"{grid.shape[1]} {grid.shape[0]}\n255\n".encode())
        fh.write(flipped.tobytes())


def write_yaml(path, image_name, resolution, origin):
    with open(path, "w") as fh:
        fh.write(f"image: {image_name}\n")
        fh.write("mode: trinary\n")
        fh.write(f"resolution: {resolution}\n")
        fh.write(f"origin: [{origin[0]:.4f}, {origin[1]:.4f}, 0.0]\n")
        fh.write("negate: 0\n")
        fh.write("occupied_thresh: 0.65\n")
        fh.write("free_thresh: 0.25\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--stage", required=True)
    ap.add_argument("--out", required=True, help="path without extension")
    ap.add_argument("--resolution", type=float, default=0.05,
                    help="metres per cell; match the costmaps, which use 0.05")
    args = ap.parse_args()

    walls = read_walls(args.stage)
    grid, origin = rasterise(walls, args.resolution)

    out = os.path.abspath(args.out)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    write_pgm(out + ".pgm", grid)
    write_yaml(out + ".yaml", os.path.basename(out) + ".pgm", args.resolution, origin)

    cell = args.resolution ** 2
    free = int((grid == FREE).sum())
    print(f"  {os.path.basename(args.stage)}: 벽 {len(walls)}개")
    print(f"  {grid.shape[1]} x {grid.shape[0]} 셀 @ {args.resolution} m   "
          f"origin [{origin[0]:.2f}, {origin[1]:.2f}]")
    print(f"  free {free * cell:.1f} m2   occupied {(grid == OCCUPIED).sum() * cell:.1f} m2")
    print(f"  wrote {out}.pgm / {out}.yaml")

    # What the widths actually became, since that is the quantity under test.
    widths = sorted({round(v, 3) for v in free_runs(grid, args.resolution, 0)
                     if v < 2.0})
    print("\n  격자에 나타난 통로 폭 (2.0 m 미만, 세로 방향):")
    print("   ", "  ".join(f"{v:.2f}" for v in widths[:14]))
    print("  0.05 m 격자이므로 설계값과 최대 한 셀 차이가 납니다.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
